import { useState } from 'react'
import useStore from '../../store/useStore'
import { platform } from '../../platform'
import { APP_NAME, APP_VERSION } from '../../version'

const EXPORT_MODES = [
  { id: 'full',     label: 'Full color',      desc: 'All devices and cables in their assigned colors' },
  { id: 'engineer', label: 'For FOH engineer', desc: 'House gear highlighted, band gear greyed out' },
  { id: 'band',     label: 'For band',         desc: 'Personal gear highlighted, house gear greyed out' },
  { id: 'rider',    label: 'Rider only',       desc: 'Technical rider as HTML document' },
  { id: 'all',      label: 'Export all',       desc: 'Stage plan + rider as separate files' },
]

export default function StageExportModal() {
  const { closeModal, stageData, settings, projectName } = useStore()
  const [mode, setMode]       = useState('engineer')
  const [exporting, setExp]   = useState(false)
  const [error, setError]     = useState(null)

  const fohColor      = settings.stageFohColor      || '#EF4444'
  const personalColor = settings.stagePersonalColor || '#6366f1'

  // Build rider HTML
  const buildRiderHtml = () => {
    const r = stageData.rider || {}
    const sections = [
      ['Technical Requirements', r.techRequirements],
      ['Monitoring',             r.monitoring],
      ['Backline',               r.backline],
      ['Contact',                r.contact],
      ['Notes',                  r.notes],
    ].filter(([, v]) => v?.trim())

    return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8">
<title>${projectName} — Technical Rider</title>
<style>
  body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; color: #111; }
  h1 { font-size: 22px; border-bottom: 2px solid #111; padding-bottom: 8px; }
  h2 { font-size: 15px; text-transform: uppercase; letter-spacing: 1px; margin-top: 28px; color: #444; }
  p  { white-space: pre-wrap; line-height: 1.7; }
  .meta { color: #888; font-size: 12px; margin-top: 4px; }
</style>
</head>
<body>
<h1>${projectName} — Technical Rider</h1>
<div class="meta">Generated by ${APP_NAME} ${APP_VERSION}</div>
${sections.map(([title, text]) => `<h2>${title}</h2><p>${text}</p>`).join('\n')}
</body></html>`
  }

  // Build stage plan SVG-based HTML export
  const buildStagePlanHtml = (exportMode) => {
    const nodes = stageData.nodes || []
    const edges = stageData.edges || []

    // Determine color per node based on export mode
    const nodeColor = (node) => {
      if (node.type === 'stageBackground' || node.type === 'stageOutline') return null
      const role = node.data?.stageRole
      if (exportMode === 'full') {
        return role === 'foh' ? fohColor : role === 'personal' ? (node.data.stageColor || personalColor) : '#888'
      }
      if (exportMode === 'engineer') {
        return role === 'foh' ? fohColor : '#ccc'
      }
      if (exportMode === 'band') {
        return role === 'personal' ? (node.data.stageColor || personalColor) : '#ccc'
      }
      return '#888'
    }

    const edgeColor = (edge) => {
      if (exportMode === 'full') return edge.data?.color || '#888'
      if (exportMode === 'engineer') return edge.data?.stageRole === 'foh' ? fohColor : '#ddd'
      if (exportMode === 'band')     return edge.data?.stageRole === 'personal' ? (edge.data.color || personalColor) : '#ddd'
      return '#888'
    }

    // Find bounds
    const deviceNodes = nodes.filter(n => n.type === 'stageDevice')
    const outline = nodes.find(n => n.type === 'stageBackground' || n.type === 'stageOutline')
    const pad = 60

    const allX = deviceNodes.map(n => n.position.x)
    const allY = deviceNodes.map(n => n.position.y)
    const minX = Math.min(...allX, outline?.position.x || 0) - pad
    const minY = Math.min(...allY, outline?.position.y || 0) - pad
    const maxX = Math.max(...allX.map((x,i) => x + 80), outline ? (outline.position.x + (outline.data.width||600)) : 0) + pad
    const maxY = Math.max(...allY.map((y,i) => y + 80), outline ? (outline.position.y + (outline.data.height||400)) : 0) + pad
    const W = maxX - minX
    const H = maxY - minY

    const tx = (x) => x - minX
    const ty = (y) => y - minY

    const svgEdges = edges.map(edge => {
      const src = nodes.find(n => n.id === edge.source)
      const tgt = edge.target ? nodes.find(n => n.id === edge.target) : null
      if (!src) return ''
      const x1 = tx(src.position.x + 40)
      const y1 = ty(src.position.y + 40)
      const x2 = tgt ? tx(tgt.position.x + 40) : x1 + 80
      const y2 = tgt ? ty(tgt.position.y + 40) : y1
      const col = edgeColor(edge)
      return `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${col}" stroke-width="1.5" stroke-opacity="0.9"/>`
        + (edge.data?.label ? `<text x="${(x1+x2)/2}" y="${(y1+y2)/2 - 6}" fill="${col}" font-size="9" text-anchor="middle">${edge.data.label}</text>` : '')
    }).join('\n')

    const svgNodes = deviceNodes.map(node => {
      const x = tx(node.position.x)
      const y = ty(node.position.y)
      const col = nodeColor(node)
      const label = node.data?.label || 'Device'
      const role  = node.data?.stageRole
      const badge = role === 'foh' ? 'H' : role === 'personal' ? 'P' : ''
      return `<g transform="translate(${x},${y})">
  <rect width="80" height="60" rx="6" fill="white" stroke="${col}" stroke-width="2"/>
  <text x="40" y="44" font-size="9" font-weight="bold" text-anchor="middle" fill="${col}">${label}</text>
  ${badge ? `<circle cx="10" cy="10" r="8" fill="${col}"/><text x="10" y="14" font-size="9" font-weight="bold" text-anchor="middle" fill="white">${badge}</text>` : ''}
</g>`
    }).join('\n')

    const svgOutline = outline ? (() => {
      const x = tx(outline.position.x)
      const y = ty(outline.position.y)
      const w = outline.data.width || 600
      const h = outline.data.height || 400
      const dir = outline.data.fohDirection || 'bottom'
      const arrows = {
        bottom: `<text x="${x+w/2}" y="${y+h-8}" font-size="11" text-anchor="middle" fill="#666">▼ FOH / Audience</text>`,
        top:    `<text x="${x+w/2}" y="${y+16}" font-size="11" text-anchor="middle" fill="#666">▲ FOH / Audience</text>`,
        left:   `<text x="${x+12}" y="${y+h/2}" font-size="11" text-anchor="start" fill="#666" transform="rotate(-90,${x+12},${y+h/2})">◀ FOH</text>`,
        right:  `<text x="${x+w-12}" y="${y+h/2}" font-size="11" text-anchor="end" fill="#666" transform="rotate(90,${x+w-12},${y+h/2})">FOH ▶</text>`,
      }
      return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="8" fill="none" stroke="#bbb" stroke-width="2" stroke-dasharray="8 4"/>
  <text x="${x+w/2}" y="${y+18}" font-size="11" font-weight="bold" text-anchor="middle" fill="#aaa" letter-spacing="2">${outline.data.label||'STAGE'}</text>
  ${arrows[dir]||''}`
    })() : ''

    const modeLabel = EXPORT_MODES.find(m => m.id === exportMode)?.label || ''

    return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8">
<title>${projectName} — Stage Plan (${modeLabel})</title>
<style>
  body { font-family: Arial, sans-serif; margin: 32px; background: white; }
  h1 { font-size: 18px; margin: 0 0 4px; }
  .meta { color: #888; font-size: 11px; margin-bottom: 24px; }
  svg { display: block; max-width: 100%; border: 1px solid #eee; border-radius: 8px; }
</style>
</head>
<body>
<h1>${projectName} — Stage Plan</h1>
<div class="meta">${modeLabel} · Generated by ${APP_NAME} ${APP_VERSION}</div>
<svg width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg">
  <rect width="${W}" height="${H}" fill="white"/>
  ${svgOutline}
  ${svgEdges}
  ${svgNodes}
</svg>
</body></html>`
  }

  const doExport = async () => {
    setExp(true)
    setError(null)
    try {
      if (mode === 'rider') {
        await platform.exportImage(buildRiderHtml(), { format: 'html', defaultName: `${projectName}-rider` })
      } else if (mode === 'all') {
        await platform.exportImage(buildStagePlanHtml('engineer'), { format: 'html', defaultName: `${projectName}-stage-engineer` })
        await platform.exportImage(buildStagePlanHtml('band'),     { format: 'html', defaultName: `${projectName}-stage-band` })
        await platform.exportImage(buildRiderHtml(),               { format: 'html', defaultName: `${projectName}-rider` })
      } else {
        await platform.exportImage(buildStagePlanHtml(mode), { format: 'html', defaultName: `${projectName}-stage-${mode}` })
      }
      closeModal()
    } catch (e) {
      setError(e.message || 'Export failed')
    } finally {
      setExp(false)
    }
  }

  return (
    <div className="modal-backdrop" onMouseDown={closeModal}>
      <div className="modal modal-sm" onMouseDown={e => e.stopPropagation()} style={{maxWidth:440}}>
        <div className="modal-header">
          <span>🎸 Export Stage</span>
          <button className="modal-close" onClick={closeModal}>×</button>
        </div>
        <div className="modal-body" style={{padding:'12px 24px 16px'}}>
          <div style={{display:'flex',flexDirection:'column',gap:6}}>
            {EXPORT_MODES.map(m => (
              <label key={m.id} style={{
                display:'flex',alignItems:'flex-start',gap:12,padding:'10px 12px',
                borderRadius:7,cursor:'pointer',border:'1px solid',
                borderColor: mode===m.id ? 'var(--accent)' : 'var(--border)',
                background: mode===m.id ? 'var(--bg-active)' : 'transparent',
              }}>
                <input type="radio" name="exportMode" value={m.id}
                  checked={mode===m.id} onChange={() => setMode(m.id)}
                  style={{marginTop:2,accentColor:'var(--accent)'}} />
                <div>
                  <div style={{fontSize:13,fontWeight:600,color:'var(--text-primary)'}}>{m.label}</div>
                  <div style={{fontSize:11,color:'var(--text-secondary)',marginTop:2}}>{m.desc}</div>
                </div>
              </label>
            ))}
          </div>

          {/* Color preview */}
          <div style={{marginTop:12,padding:'10px 12px',background:'var(--bg-input)',borderRadius:7,fontSize:11,color:'var(--text-secondary)'}}>
            {mode === 'engineer' && <>House gear highlighted in <span style={{color:fohColor,fontWeight:700}}>■</span> {fohColor}, band gear greyed out</>}
            {mode === 'band'     && <>Personal gear highlighted in <span style={{color:personalColor,fontWeight:700}}>■</span> {personalColor}, house gear greyed out</>}
            {mode === 'full'     && <>All gear in their assigned role colors</>}
            {mode === 'rider'    && <>Technical rider document only, no stage diagram</>}
            {mode === 'all'      && <>Exports 3 files: stage for engineer, stage for band, rider</>}
          </div>

          {error && <div style={{marginTop:8,color:'var(--danger)',fontSize:12}}>⚠ {error}</div>}
        </div>
        <div className="modal-footer">
          <button className="props-btn" onClick={closeModal}>Cancel</button>
          <button className="props-btn accent" onClick={doExport} disabled={exporting}>
            {exporting ? 'Exporting…' : '↓ Export'}
          </button>
        </div>
      </div>
    </div>
  )
}
