export const CABLE_TYPES = {
  XLR:     { label: 'XLR (Balanced)',       color: '#3B82F6', dash: null,       desc: 'Balanced audio, mics, line level',
             compatible: ['XLR', 'XLR-M', 'XLR-F', 'XLR3', 'XLR5'] },
  TRS:     { label: 'Jack TRS (Balanced)',   color: '#10B981', dash: null,       desc: 'Balanced 1/4", inserts, headphones',
             compatible: ['TRS', 'Jack TRS', '1/4" TRS', 'Mini TRS', '3.5mm TRS'] },
  TS:      { label: 'Jack TS (Instrument)',  color: '#F59E0B', dash: null,       desc: 'Unbalanced instrument cable',
             compatible: ['TS', 'Jack TS', '1/4" TS', 'Jack'] },
  MIDI:    { label: 'MIDI',                  color: '#F97316', dash: '6 3',      desc: '5-pin DIN MIDI',
             compatible: ['MIDI', 'DIN 5', '5-pin DIN'] },
  USB:     { label: 'USB',                   color: '#8B5CF6', dash: null,       desc: 'USB A/B/C',
             compatible: ['USB', 'USB-A', 'USB-B', 'USB-C', 'USB Micro', 'USB Mini'] },
  OPTICAL: { label: 'Optical / TOSLINK',     color: '#06B6D4', dash: '2 4',      desc: 'ADAT, S/PDIF optical',
             compatible: ['TOSLINK', 'Optical', 'ADAT'] },
  HDMI:    { label: 'HDMI / Video',          color: '#EC4899', dash: null,       desc: 'Video signal',
             compatible: ['HDMI', 'Mini HDMI', 'Micro HDMI'] },
  AES:     { label: 'AES/EBU',              color: '#EF4444', dash: '8 3',      desc: 'Professional digital audio',
             compatible: ['XLR', 'XLR-M', 'XLR-F', 'AES/EBU'] },
  DANTE:   { label: 'Dante / AVB',           color: '#14B8A6', dash: '5 2 1 2', desc: 'Network audio (Ethernet)',
             compatible: ['RJ45', 'Ethernet', 'Dante', 'AVB'] },
  SPEAKER: { label: 'Speaker Cable',         color: '#DC2626', dash: null,       desc: 'Amp to speaker, unbalanced',
             compatible: ['Speakon', 'NL2', 'NL4', 'NL8', 'Banana', 'Bare wire', 'TS', 'Jack TS'] },
  POWER:   { label: 'Power / IEC',           color: '#6B7280', dash: '3 3',      desc: 'Mains power',
             compatible: ['IEC', 'IEC C13', 'IEC C14', 'Powercon', 'Powercon TRUE1', 'Schuko', 'NEMA'] },
}

export const CABLE_GROUPS = {
  'Analog':        ['XLR', 'TRS', 'TS', 'SPEAKER'],
  'Digital':       ['MIDI', 'USB', 'OPTICAL', 'AES', 'DANTE'],
  'Video / Power': ['HDMI', 'POWER'],
}
